Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr = np.array([1,2,3,4,5])
print(arr)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
import random
arr= np.zeros((3,4))
for i in range(3):
  for j in range (4):
    arr[i][j]= random.randint(1,10)

print(arr)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr= np.zeros((3,4))
print(arr)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr= np.ones((3,4))
print(arr)


[[ 8.  2. 10.  4.]
 [ 6.  8.  8.  4.]
 [ 7.  4.  1.  7.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:

 # Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
arr= np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
print(np.add(a,b))
print("\n")
print(np.subtract(a,b))
print("\n")
print(np.multiply(a,b)) # element wise multiplication
print("\n")
print(np.dot(a,b)) # matrix multiplication
print("\n")
print(np.divide(a,b))

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]


[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]


[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]


[[ 984  542 1014]
 [ 430  303  480]
 [1036  552 1041]]


[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
arr= a.sum(axis=0)
print(arr)
# Write a NumPy function to get the sum of the array 'a' along axis=1
arr= a.sum(axis=1)
print(arr)

[ 5 17  6]
[10  4 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'
arr= np.flip(a)
print(arr)
print("\n")
# Write a NumPy function to reverse the array 'a' along axis=0
arr= np.flip(a,axis=0)
print(arr)
print("\n")
# Write a NumPy function to reverse the array 'a' along axis=1
arr= np.flip(a,axis=1)
print(arr)
print("\n")

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]


[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]


[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]




### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
arr1= np.sort(a, axis= None)
print(arr1)
print("\n")
# Write a NumPy function to sort the array 'a' along axis=0
arr2= np.sort(a, axis= 0)
print(arr2)
print("\n")
# Write a NumPy function to sort the array 'a' along axis=1

arr3= np.sort(a, axis= 1)
print(arr3)
print("\n")
# Write a NumPy function to sort the array 'a' in descending order along axis=0
arr= np.sort(a, axis= 0)
arr=np.flip(arr,axis=0)
print(arr)
print("\n")

[-4  1  1  3  5  6  8  8  9]


[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]


[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]


[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]




In [ ]:
# Write a NumPy function to argsort the array along axis=0
import numpy as np
np.argsort(a,axis=0)
# Write a NumPy function to argsort the array along axis=1
np.argsort(a,axis=1)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
arr = np.concatenate(a,b)
print(arr)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
arr = np.concatenate((a,b),axis=0)
# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)
# Write a NumPy function to get the Shape of the array
print(a.shape)
# Write a NumPy function to get the Size of the array
print(a.size)

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension
print(a.reshape(1,9))

[[4 6 8 9 3 1 1 8 5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
y=np.expand_dims(a, axis=0)
print(y.shape)

z= np.expand_dims(a,axis=(0,3,4))
print(z.shape)

(1, 3, 3)
(1, 3, 3, 1, 1)


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
arr= a[[0,1,2],[0,1,2]]
print(arr)

[4 3 5]


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a>4])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
arr= a[a>4]
arr= arr[arr%2==0]
print(arr)

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
arr= a.copy()
one= np.ones((3,3))
print(np.add(arr,one))

[[5. 7. 1.]
 [1. 4. 2.]
 [2. 9. 6.]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df=pd.DataFrame(iris_2d)
new_df=df.dropna()
print(new_df.to_string())

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
print(df[0].corr(df[1]))

-0.10936924995064937


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print(df[2].mean()) #Mean
print(df[2].median()) #Median
print(df[2].std()) #Standard deviation

3.758666666666666
4.35
1.7644204199522626


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
df2= pd.DataFrame(index=range(150),columns=range(5))
for x in range(150) :
  for j in range(4):
    (df2.loc[x]).loc[j]= (df.loc[x]).loc[j]
for x in range(150) :
  (df2.loc[x]).loc[4]= (3.14)*((df.loc[x]).loc[2])*((df.loc[x]).loc[0])*((df.loc[x]).loc[0])/3
print(df2)

       0    1    2    3           4
0    5.1  3.5  1.4  0.2    38.11332
1    4.9  3.0  1.4  0.2   35.182653
2    4.7  3.2  1.3  0.2   30.057127
3    4.6  3.1  1.5  0.2     33.2212
4    5.0  3.6  1.4  0.2   36.633333
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.321307
146  6.3  2.5  5.0  1.9     207.711
147  6.5  3.0  5.2  2.0  229.952667
148  6.2  3.4  5.4  2.3   217.26288
149  5.9  3.0  5.1  1.8   185.81578

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
import numpy as np
arr= np.ones(4, dtype=np.int64)
print(arr)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x= np.array([1,2,3,4,5,6,7,8,9])
arr1= x[:4]
arr2= x[4:6]
arr3= x[6:]
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4]
[5 6]
[7 8 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
import pandas as pd
df=pd.DataFrame(iris, columns=names)
print(df("species").nunique)

TypeError: 'DataFrame' object is not callable

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
import pandas as pd
df=pd.DataFrame(iris, columns=names)
pd.cut(df["petallength"],bins=[0,3,5,float('inf')])

TypeError: '<' not supported between instances of 'float' and 'bytes'

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset